name: ZoneMusicPlayer
version: 1.0.0
main: fr.yotapaki.ZoneMusicPlayer.Main
description: An example plugin
author: Yotapaki
website: https://romain-guillemot.dev
api-version: '1.20.6'

commands:
  zonemusic:
    description: Manage ZoneMusicPlayer settings and play sounds.
    usage: /zonemusic <reload|debug|play>
    aliases: [zm]
    permission: zonemusic.use
permissions:
  zonemusic.use:
    description: Allows access to ZoneMusicPlayer commands.
    default: true
  zonemusic.reload:
    description: Allows reloading the plugin configuration.
    default: op
  zonemusic.debug:
    description: Allows toggling debug mode.
    default: op
  zonemusic.play:
    description: Allows playing custom sounds for players.
    default: op

depend:
  - WorldGuard
